name = "grow-a-garden-calculator"
main = "worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
watch_dir = "src"

[site]
bucket = ".next"

[env.production]
name = "grow-a-garden-calculator-prod"

[env.staging]
name = "grow-a-garden-calculator-staging"

[build.upload]
format = "modules"
dir = ".next"
main = "worker.js"
rules = [
  { type = "ESModule", globs = ["**/*.js"], fallthrough = true },
  { type = "Text", globs = ["**/*.html", "**/*.css"], fallthrough = true },
  { type = "Data", globs = ["**/*"], fallthrough = true }
]

[miniflare]
kv_persist = true
cache_persist = true

[[kv_namespaces]]
binding = "ASSETS"
id = "assets"

[[d1_databases]]
binding = "DB"
database_name = "garden-calculator"
database_id = "" 