version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./public:/app/public  # 动态挂载 public 目录
    networks:
      - frontend

networks:
  frontend:
    driver: bridge